### PR TITLE
Add AIData description property to class

### PR DESCRIPTION
**Pull request by einar-hansen**
Add the description string as a property to the AIData class, as later versions of PHP triggers a deprecation warning for dynamic properties.

### CODE REVIEW

**Comment by jsgoupil** [comment]
Thanks for proposing this contribution.
The field you are adding is private, it means you are technically having the code locally are able to change the data in your repository.
Since we do not use this `description` property, it would not be beneficial to add it to our repo.

I would recommend you extend the `AIData` class and add the `description` in your class.

**Comment by einar-hansen** [comment]
Hi! Not quite sure what you are meaning, but you are already using this property in the class (look at the constructor). As it is not declared, it is being interpreted as a dynamic property by PHP. By declaring the property you then avoid the runtime warning ;)

**Comment by jsgoupil** [comment]
Ah yes! Sorry I didn't see the constructor in the code review.
You are right and it's a bug!

I will merge this soon and release a new patch. 

Thank you very much!

**Comment by jsgoupil** [comment]
I have updated the version to 7.0.4.
I won't ship new versions of each packages on our site because the main user is https://github.com/barcode-bakery/utility-php-gs1ai
Which I have updated to version 2.

Thank you for your contribution!

**Pull request merged**
